spring.application.name=PlateformRH
server.port= 8000
  spring.datasource.url=jdbc:mysql://localhost:3306/talentmatch?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=95759khmiletttH_g
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update



#config api mailing
spring.mail.username=mohamedsalhiii66@gmail.com 
spring.mail.password=wqiu cweh lxfx xsqu
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.root=INFO
logging.level.org.springframework.security=DEBUG
logging.level.com.PlateformRH=DEBUG


