spring.application.name=PlateformRH
server.port= 8000
  spring.datasource.url=jdbc:mysql://localhost:3306/talentmatch?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=95759khmiletttH_g
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update



#config api mailing
spring.mail.username=mohamedsalhiii66@gmail.com 
spring.mail.password=wqiu cweh lxfx xsqu
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.root=INFO
logging.level.org.springframework.security=DEBUG
logging.level.com.PlateformRH=DEBUG


#je veux changer le thème de home component, mélange entre dark (bleu foncé) et light avec des couleurs vivantes (orangé, bleu clair, violet) tout d'abord le nav bar, ensuite des photos montés en video comme des reunions, un homme avec son pc donc dans ce genre, ensuite une petite section à propos de l'entreprise, apres une section carrières où les offres externes s'affichent donc la description ne s'affiche que les deux premieres lignes avec les compétences, niveau... et un bouton voir plux qui affiche un nouvel component les details de l'offre et un bouton postuler pour passer à un formulaire, et les autres sections comme toute entreprise